include $(srctree)/scripts/Kbuild.include
include $(src)/Makefile

quiet_cmd_dtb_install = INSTALL $@
cmd_dtb_install = install -D $< $@

dtbos := $(addprefix $(dst)/, $(dtbo-y))
subdirs := $(addprefix $(obj)/, $(subdir-y))

$(dst)/%.dtbo: $(obj)/%.dtbo FORCE
	$(call cmd,dtb_install)

.PHONY: $(subdirs)
$(subdirs): FORCE
	$(Q)$(MAKE) -f Makefile.install src=$@ obj=$@ \
		dst=$(patsubst $(obj)/%,$(dst)/%,$@) all

all: $(subdirs) $(dtbos) FORCE

.PHONY: FORCE
FORCE:

# vim: filetype=make
