dtbo-y += \
	blueled_off.dtbo \
	can0.dtbo \
	circuitpython.dtbo \
	dht11.dtbo \
	display_vu8m.dtbo \
	display_waveshare_1inch47.dtbo \
	display_waveshare_1inch69.dtbo \
	fiq0_to_uart2.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	onewire.dtbo \
	ov5647.dtbo \
	pcf8563.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm9.dtbo \
	rknpu.dtbo \
	spi0.dtbo \
	ttyfiq0_115200.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	weather_board_zero.dtbo
